#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side


# AutoStart
$HOME/.config/polybar/launch.sh &
ibus-daemon -drx
sxhkd &
nitrogen --restore &
dunst &
picom --config $HOME/.config/picom/picom.conf &
